version: '3.1'

services:
    postgresql:
        build: ./docker/postgresql    
        container_name: 'task-postgresql'
        ports:
          - "5432:5432"
        volumes: 
          - postgres_data:/var/lib/postgresql/data
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: homestead
          PGDATA: /var/lib/postgresql/data
        networks:
          task_net:
              ipv4_address: 172.1.2.2

volumes:
  postgres_data:

networks:
    task_net:
      ipam:
          driver: default
          config:
              - subnet: 172.1.2.0/24